# Generated by Django 6.0 on 2026-01-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_farmerprofile_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='crops',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='farmers/'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='farmers/'),
        ),
    ]
